language: java
sudo: false
jdk:
  - oraclejdk8
install: true
script: "./gradle/buildViaTravis.sh"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_832b02c80e0c_key -iv $encrypted_832b02c80e0c_iv
  -in gradle.properties.enc -out gradle.properties -d || true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/67add3390223c819bbe8
    on_success: change
    on_failure: always
    on_start: never
